services:
  mongodb:
    image: mongo:5.0 
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo_data:/data/db